# escape=`

ARG WINDOWS_BASE_IMAGE=mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2022
ARG WEBRTC_IMAGE=ghcr.io/general-fault/webrtc:latest

FROM ${WEBRTC_IMAGE} AS webrtc-artifacts

FROM ${WINDOWS_BASE_IMAGE} AS webrtcnet-builder

SHELL ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "-NoLogo", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"]

ENV CHOCOLATEY_USE_WINDOWS_COMPRESSION=false `
    WEBRTC_SRC_PATH=C:\opt\webrtc\src `
    WEBRTC_OUT_PATH=C:\opt\webrtc\out `
    WEBRTC_PREBUILT=1

# Build tools and the .NET SDK needed to compile the managed + C++/CLI layers.
RUN $ErrorActionPreference = 'Stop'; `
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072; `
    Set-ExecutionPolicy Bypass -Scope Process -Force; `
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1')); `
    choco feature enable -n allowGlobalConfirmation; `
    choco install -y git python3; `
    New-Item -ItemType Directory -Force C:\TEMP | Out-Null; `
    $installer = 'C:\TEMP\vs_buildtools.exe'; `
    Invoke-WebRequest -Uri 'https://aka.ms/vs/17/release/vs_buildtools.exe' -OutFile $installer; `
    Start-Process -FilePath $installer -Wait -ArgumentList '--quiet', '--wait', '--norestart', '--nocache', '--installPath', 'C:\BuildTools', '--add', 'Microsoft.VisualStudio.Workload.NativeDesktop', '--add', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', '--add', 'Microsoft.VisualStudio.Component.VC.CLI.Support', '--add', 'Microsoft.Net.Component.4.5.TargetingPack', '--add', 'Microsoft.Net.Component.4.7.TargetingPack', '--add', 'Microsoft.VisualStudio.Component.Windows10SDK.20348', '--add', 'Microsoft.VisualStudio.Component.Windows11SDK.22621', '--add', 'Microsoft.VisualStudio.Component.Windows11SDK.26100', '--includeRecommended'; `
    Remove-Item $installer -Force

COPY . C:\workspace
RUN New-Item -ItemType Directory -Force C:\opt\webrtc\out\Release\x64\obj | Out-Null
COPY --from=webrtc-artifacts C:\artifacts\src C:\opt\webrtc\src
COPY --from=webrtc-artifacts C:\artifacts\out\Release\x64\obj\webrtc.lib C:\opt\webrtc\out\Release\x64\obj\webrtc.lib
COPY docker\build-webrtcnet.ps1 C:\build\build-webrtcnet.ps1

WORKDIR C:\workspace

RUN & C:\build\build-webrtcnet.ps1
