# escape=`

ARG WEBRTC_ARTIFACTS_IMAGE=ghcr.io/general-fault/webrtc:msvc-shared-7778
ARG WEBRTCNET_BASE_IMAGE=mcr.microsoft.com/dotnet/sdk:10.0.300-windowsservercore-ltsc2025

FROM ${WEBRTC_ARTIFACTS_IMAGE} AS webrtc-artifacts

FROM ${WEBRTCNET_BASE_IMAGE} AS webrtcnet-builder

SHELL ["pwsh.exe", "-NoLogo", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"]

# Install VS Build Tools to C:\BuildTools with C++/CLI support and .NET targeting packs.
# C:\BuildTools is the install path expected by docker\build-webrtcnet.ps1.
RUN curl -fSLo vs_BuildTools.exe https://aka.ms/vs/stable/vs_BuildTools.exe `
    && start /w vs_BuildTools ^ `
        --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\18\BuildTools" ^ `
        #--add Microsoft.Net.Component.4.8.1.SDK ^ `
        --add Microsoft.VisualStudio.Workload.MSBuildTools ^ `
        --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core ^ `
        --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.ARM ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 ^ `
        --add Microsoft.VisualStudio.Component.Windows11SDK.26100 ^ `
        #--add Microsoft.VisualStudio.Component.TestTools.BuildTools ^ `
        --add Microsoft.VisualStudio.Component.VC.CLI.Support ^ `
        --add Microsoft.Net.Component.4.8.1.SDK ^ `
        --quiet --norestart --nocache --wait `
    && pwsh -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del vs_BuildTools.exe `
    `
    # Cleanup
    && (for /D %i in ("%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\*") do rmdir /S /Q "%i") `
    && (for %i in ("%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\*") do if not "%~nxi" == "vswhere.exe" del "%i") `
    && (for /D %i in ("%TEMP%\*") do rmdir /S /Q "%i") && (for %i in ("%TEMP%\*") do del /Q "%i")


ENV `
    WEBRTC_SRC_PATH=C:\webrtc-artifacts\include `
    WEBRTC_OUT_PATH=C:\webrtc-artifacts\lib `
    WEBRTC_PREBUILT=1

COPY --from=webrtc-artifacts C:\webrtc-artifacts\include C:\webrtc-artifacts\include
COPY --from=webrtc-artifacts C:\webrtc-artifacts\lib C:\webrtc-artifacts\lib

COPY . C:\workspace
COPY docker\build-webrtcnet.ps1 C:\build\build-webrtcnet.ps1

WORKDIR C:\workspace

RUN & C:\build\build-webrtcnet.ps1
