# escape=`

ARG TOOLCHAIN_BASE_IMAGE=mcr.microsoft.com/dotnet/sdk:10.0.300-windowsservercore-ltsc2025
ARG DEPOT_TOOLS_PATH=C:\depot_tools

#Stage 1: Build the toolchain image with VS Build Tools, SDKs, depot_tools, git, python, and Chocolatey
FROM ${TOOLCHAIN_BASE_IMAGE} AS webrtc-toolchain

ARG DEPOT_TOOLS_PATH

ENV CHOCOLATEY_USE_WINDOWS_COMPRESSION=false `
    DEPOT_TOOLS_PATH=${DEPOT_TOOLS_PATH} `
    DEPOT_TOOLS_WIN_TOOLCHAIN=0

# Install VS Build Tools with C++ and Windows SDKs
RUN curl -fSLo vs_BuildTools.exe https://aka.ms/vs/stable/vs_BuildTools.exe `
    && start /w vs_BuildTools ^ `
        --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\18\BuildTools" ^ `
        #--add Microsoft.Net.Component.4.8.1.SDK ^ `
        --add Microsoft.VisualStudio.Workload.MSBuildTools ^ `
        --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core ^ `
        --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.ARM ^ `
        --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 ^ `
        --add Microsoft.VisualStudio.Component.Windows11SDK.26100 ^ `
        #--add Microsoft.VisualStudio.Component.TestTools.BuildTools ^ `
        --quiet --norestart --nocache --wait `
    && pwsh -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }" `
    && del vs_BuildTools.exe `
    `
    # Workaround for issues with 64-bit ngen
    #&& %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen uninstall "%ProgramFiles(x86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\SecAnnotate.exe" `
    #&& %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen uninstall "%ProgramFiles(x86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8.1 Tools\WinMDExp.exe" `
    #`
    # ngen assemblies queued by VS installers
    #&& %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen update `
    `
    # Cleanup
    && (for /D %i in ("%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\*") do rmdir /S /Q "%i") `
    && (for %i in ("%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\*") do if not "%~nxi" == "vswhere.exe" del "%i") `
    && (for /D %i in ("%TEMP%\*") do rmdir /S /Q "%i") && (for %i in ("%TEMP%\*") do del /Q "%i")

# Install the Windows SDK debugging tools needed by vs_toolchain CopyDlls.
RUN curl -fSLo winsdksetup.exe https://go.microsoft.com/fwlink/?linkid=2361308 `
    && start /w winsdksetup.exe /features OptionId.WindowsDesktopDebuggers /quiet /norestart `
    && del /Q winsdksetup.exe `
    && (for /D %i in ("%TEMP%\*") do rmdir /S /Q "%i") && (for %i in ("%TEMP%\*") do del /Q "%i") `
    && (for /D %i in ("%WINDIR%\Temp\*") do rmdir /S /Q "%i") && (for %i in ("%WINDIR%\Temp\*") do del /Q "%i")

# Set PATH in one layer to keep image size down.
RUN pwsh -Command `
    setx /M PATH $(${Env:PATH} `
    + \";${Env:ProgramFiles}\NuGet\" `
    + \";${Env:ProgramFiles(x86)}\Microsoft Visual Studio\18\BuildTools\MSBuild\Current\Bin\amd64\" `
    + \";${Env:ProgramFiles(x86)}\Microsoft Visual Studio\18\BuildTools\Common7\IDE\Extensions\TestPlatform\")
   
# Remove MinGit and cleanup the PATH variable
RUN rmdir /S /Q "C:\Program Files\MinGit" && set "PATH=%PATH:C:\Program Files\MinGit\cmd;=%" && setx /M PATH "%PATH%"

# Install the latest version of Git for Windows.
RUN curl -fSLo Git-2.54.0-64-bit.exe https://github.com/git-for-windows/git/releases/download/v2.54.0.windows.1/Git-2.54.0-64-bit.exe `
    && start /w Git-2.54.0-64-bit.exe /VERYSILENT /NORESTART /NOCANCEL /SP- `
    && del /Q Git-2.54.0-64-bit.exe

# Configure git for WebRTC checkout and local patch application.
RUN git config --global core.autocrlf false `
    && git config --global core.filemode false `
    && git config --global core.longpaths true `
    && git config --global user.name "Cody Barnes" `
    && git config --global user.email "conceptgenesis@gmail.com"

# Clone depot_tools, add it to PATH, mark it safe, allow global git config,
# then run gclient from cmd.exe to trigger the CIPD bootstrap (installs
# Python, generates git.bat, etc.). DEPOT_TOOLS_UPDATE must NOT be set here.
RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git %DEPOT_TOOLS_PATH% `
    && setx /M PATH "%DEPOT_TOOLS_PATH%;%PATH%" `
    && git config --global --add safe.directory %DEPOT_TOOLS_PATH% `
    && git config --global depot-tools.allowGlobalGitConfig true `
    && cmd /S /C "set PATH=%DEPOT_TOOLS_PATH%;%PATH% && set DEPOT_TOOLS_WIN_TOOLCHAIN=0 && gclient"

LABEL org.opencontainers.image.description="WebRtc toolchain base image with VS Build Tools, SDK 10.0.300+, depot_tools, git, python 3.0, Chocolatey"
LABEL org.opencontainers.image.source="https://github.com/General-Fault/WebRtcNet"
