param(
	[string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path,
	[switch]$IncludeEditorsDraft
)

$ErrorActionPreference = "Stop"

function Save-WebDocument {
	param(
		[Parameter(Mandatory = $true)][string]$Url,
		[Parameter(Mandatory = $true)][string]$OutputPath
	)

	$directory = Split-Path -Path $OutputPath -Parent
	if (-not (Test-Path -LiteralPath $directory)) {
		New-Item -ItemType Directory -Path $directory | Out-Null
	}

	Invoke-WebRequest -Uri $Url -OutFile $OutputPath
}

function Test-Anchor {
	param(
		[Parameter(Mandatory = $true)][string]$FilePath,
		[Parameter(Mandatory = $true)][string]$Pattern
	)

	$match = Select-String -Path $FilePath -Pattern $Pattern -SimpleMatch
	if (-not $match) {
		throw "Anchor/content check failed. Pattern '$Pattern' not found in '$FilePath'."
	}
}

function Get-Hash {
	param([Parameter(Mandatory = $true)][string]$FilePath)
	return (Get-FileHash -Algorithm SHA256 -Path $FilePath).Hash
}

$specRoot = Join-Path $RepoRoot "documents\specs"
$indexLog = Join-Path $specRoot "index\update-log.md"

$downloads = @(
	@{
		Name = "WebRTC TR"
		Url = "https://www.w3.org/TR/webrtc/"
		RelativePath = "webrtc\TR-webrtc.html"
		CheckPattern = "id=""dom-rtcpeerconnection"""
	},
	@{
		Name = "Media Capture TR"
		Url = "https://www.w3.org/TR/mediacapture-streams/"
		RelativePath = "mediacapture\TR-mediacapture-streams.html"
		CheckPattern = "id=""dom-mediadevices-getusermedia"""
	},
	@{
		Name = "WebRTC Stats TR"
		Url = "https://www.w3.org/TR/webrtc-stats/"
		RelativePath = "webrtc-stats\TR-webrtc-stats.html"
		CheckPattern = "RTCStatsReport"
	},
	@{
		Name = "W3C Document License 2023"
		Url = "https://www.w3.org/copyright/document-license-2023/"
		RelativePath = "licenses\w3c-document-license-2023.html"
		CheckPattern = "Document License"
	},
	@{
		Name = "W3C Software License 2023"
		Url = "https://www.w3.org/copyright/software-license-2023/"
		RelativePath = "licenses\w3c-software-license-2023.html"
		CheckPattern = "Software and Document License"
	}
)

if ($IncludeEditorsDraft) {
	$downloads += @(
		@{
			Name = "WebRTC Editor's Draft"
			Url = "https://w3c.github.io/webrtc-pc/"
			RelativePath = "webrtc\ED-webrtc-pc.html"
			CheckPattern = "RTCPeerConnection"
		},
		@{
			Name = "Media Capture Editor's Draft"
			Url = "https://w3c.github.io/mediacapture-main/"
			RelativePath = "mediacapture\ED-mediacapture-main.html"
			CheckPattern = "MediaDevices"
		},
		@{
			Name = "WebRTC Stats Editor's Draft"
			Url = "https://w3c.github.io/webrtc-stats/"
			RelativePath = "webrtc-stats\ED-webrtc-stats.html"
			CheckPattern = "RTCStats"
		}
	)
}

$results = @()
foreach ($item in $downloads) {
	$outputPath = Join-Path $specRoot $item.RelativePath
	Save-WebDocument -Url $item.Url -OutputPath $outputPath
	Test-Anchor -FilePath $outputPath -Pattern $item.CheckPattern
	$results += [pscustomobject]@{
		Name = $item.Name
		Path = $item.RelativePath
		Url = $item.Url
		Hash = Get-Hash -FilePath $outputPath
	}
}

$date = Get-Date -Format "yyyy-MM-dd"
$logLines = @()
$logLines += ""
$logLines += "## $date - Script refresh"
$logLines += ""
$logLines += "Generated by scripts/update-spec-docs.ps1."
$logLines += ""
$logLines += "### Retrieved Documents"
$logLines += ""

$counter = 1
foreach ($result in $results) {
	$logLines += "$counter. specs/$($result.Path)"
	$logLines += "	Source: <$($result.Url)>"
	$logLines += "	SHA256: $($result.Hash)"
	$logLines += ""
	$counter++
}

$logLines += "### Validation Notes"
$logLines += ""
$logLines += "- Anchor/content checks passed for all downloaded documents."

if (-not (Test-Path -LiteralPath $indexLog)) {
	New-Item -ItemType File -Path $indexLog | Out-Null
}

Add-Content -Path $indexLog -Value $logLines

Write-Output "Updated $($results.Count) documents and appended update log at '$indexLog'."
