<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebRtcSrcRoot>$(WEBRTC_SRC_PATH)</WebRtcSrcRoot>
    <WebRtcOutRoot>$(WEBRTC_OUT_PATH)</WebRtcOutRoot>
    <WebRtcGoogletestRoot>$(WebRtcSrcRoot)\third_party\googletest\src</WebRtcGoogletestRoot>
  </PropertyGroup>
</Project>
